/**
 * ZERITHUM EXPENSE CATEGORIES
 * Covers standard creator business expense types with deductibility guidance.
 * Note: Percentages are general guidance only — not tax advice.
 */
export const CATEGORIES = {
  software_subscriptions: {
    label: "Software & Subscriptions",
    icon: "💻",
    color: "bg-blue-500/10 text-blue-400",
    description: "SaaS tools, editing software, cloud storage, design apps.",
    examples: "Adobe Creative Cloud, Final Cut Pro, Notion, Dropbox, Slack",
    deductibilityHint: "Generally 100% deductible when used exclusively for business.",
    defaultDeductible: "yes",
  },
  equipment: {
    label: "Equipment",
    icon: "🖥️",
    color: "bg-purple-500/10 text-purple-400",
    description: "Hardware, cameras, microphones, lighting, peripherals.",
    examples: "Camera, microphone, ring light, external drive, monitor",
    deductibilityHint: "May be depreciated over time or expensed via Section 179. Personal use portion is not deductible.",
    defaultDeductible: "partial",
  },
  marketing: {
    label: "Marketing & Advertising",
    icon: "📢",
    color: "bg-pink-500/10 text-pink-400",
    description: "Paid ads, promotions, sponsorship fees, PR.",
    examples: "Meta Ads, Google Ads, newsletter sponsorships, influencer pay",
    deductibilityHint: "Generally 100% deductible as ordinary business expense.",
    defaultDeductible: "yes",
  },
  professional_services: {
    label: "Professional Services",
    icon: "⚖️",
    color: "bg-indigo-500/10 text-indigo-400",
    description: "Legal, accounting, consulting, and contractor fees.",
    examples: "Accountant, lawyer, brand consultant, freelance editor",
    deductibilityHint: "Generally 100% deductible. Issue 1099 to US contractors paid > $600/year.",
    defaultDeductible: "yes",
  },
  office_supplies: {
    label: "Office Supplies",
    icon: "📎",
    color: "bg-green-500/10 text-green-400",
    description: "Stationery, small items, printer consumables.",
    examples: "Pens, notebooks, paper, ink cartridges, cables",
    deductibilityHint: "Generally deductible. Keep receipts for items over $25.",
    defaultDeductible: "yes",
  },
  travel: {
    label: "Travel & Transport",
    icon: "✈️",
    color: "bg-amber-500/10 text-amber-400",
    description: "Business travel including flights, hotels, rental cars, rideshare.",
    examples: "Flight to conference, hotel for shoot, Uber to client meeting",
    deductibilityHint: "Deductible when trip is primarily for business. Mixed trips require apportionment.",
    defaultDeductible: "partial",
  },
  meals: {
    label: "Meals & Entertainment",
    icon: "🍽️",
    color: "bg-orange-500/10 text-orange-400",
    description: "Business meals with clients, partners, or team.",
    examples: "Lunch with collaborator, coffee with client, team dinner",
    deductibilityHint: "Typically 50% deductible in the US. Entertainment (events, sports) generally not deductible.",
    defaultDeductible: "partial",
  },
  education: {
    label: "Education & Training",
    icon: "📚",
    color: "bg-cyan-500/10 text-cyan-400",
    description: "Courses, books, workshops, coaching relevant to your business.",
    examples: "MasterClass, Skillshare, business books, coaching calls",
    deductibilityHint: "Deductible when it maintains or improves required skills in your current business.",
    defaultDeductible: "yes",
  },
  internet_phone: {
    label: "Internet & Phone",
    icon: "📱",
    color: "bg-teal-500/10 text-teal-400",
    description: "Monthly internet service and phone plan used for work.",
    examples: "Home internet, mobile plan, dedicated business line",
    deductibilityHint: "Deduct the business-use percentage — typically 50–100% for full-time creators.",
    defaultDeductible: "partial",
  },
  rent_utilities: {
    label: "Rent & Utilities",
    icon: "🏢",
    color: "bg-orange-500/10 text-orange-400",
    description: "Office rent, co-working space, or home office share.",
    examples: "Studio rent, WeWork membership, proportional home office",
    deductibilityHint: "Office rent is 100% deductible. Home office requires exclusive and regular business use.",
    defaultDeductible: "partial",
  },
  platform_fees: {
    label: "Platform Fees",
    icon: "💳",
    color: "bg-slate-500/10 text-slate-400",
    description: "Transaction fees, marketplace commissions, payment processing.",
    examples: "Stripe fees, PayPal fees, Gumroad commissions, YouTube MCN cut",
    deductibilityHint: "Fully deductible as cost of doing business.",
    defaultDeductible: "yes",
  },
  other: {
    label: "Other",
    icon: "📦",
    color: "bg-gray-500/10 text-gray-400",
    description: "Expenses that don't fit into a standard category.",
    examples: "Miscellaneous business costs",
    deductibilityHint: "Deductibility depends on business purpose. Add a clear description.",
    defaultDeductible: "partial",
  },
};
