export const INPUT_STORAGE_KEY = "zerithum-tax-estimator-inputs-v1";
export const PAYMENT_STORAGE_KEY = "zerithum-tax-estimator-payment-status-v1";

export const DEFAULT_INPUTS = {
  filingStatus: "single",
  state: "CA",
  expectedAnnualRevenue: 0,
  expenseRate: 25,
  includeOtherIncome: false,
  otherIncome: 0,
};

export const DEFAULT_PAYMENT_STATUS = {
  q1: { paid: false, paidAt: null },
  q2: { paid: false, paidAt: null },
  q3: { paid: false, paidAt: null },
  q4: { paid: false, paidAt: null },
};

export const FILING_STATUS_OPTIONS = [
  { value: "single", label: "Single" },
  { value: "married_joint", label: "Married Filing Jointly" },
  { value: "married_separate", label: "Married Filing Separately" },
  { value: "head_of_household", label: "Head of Household" },
];

export const STATE_OPTIONS = [
  { value: "AL", label: "Alabama" },
  { value: "AK", label: "Alaska" },
  { value: "AZ", label: "Arizona" },
  { value: "AR", label: "Arkansas" },
  { value: "CA", label: "California" },
  { value: "CO", label: "Colorado" },
  { value: "CT", label: "Connecticut" },
  { value: "DE", label: "Delaware" },
  { value: "FL", label: "Florida" },
  { value: "GA", label: "Georgia" },
  { value: "HI", label: "Hawaii" },
  { value: "ID", label: "Idaho" },
  { value: "IL", label: "Illinois" },
  { value: "IN", label: "Indiana" },
  { value: "IA", label: "Iowa" },
  { value: "KS", label: "Kansas" },
  { value: "KY", label: "Kentucky" },
  { value: "LA", label: "Louisiana" },
  { value: "ME", label: "Maine" },
  { value: "MD", label: "Maryland" },
  { value: "MA", label: "Massachusetts" },
  { value: "MI", label: "Michigan" },
  { value: "MN", label: "Minnesota" },
  { value: "MS", label: "Mississippi" },
  { value: "MO", label: "Missouri" },
  { value: "MT", label: "Montana" },
  { value: "NE", label: "Nebraska" },
  { value: "NV", label: "Nevada" },
  { value: "NH", label: "New Hampshire" },
  { value: "NJ", label: "New Jersey" },
  { value: "NM", label: "New Mexico" },
  { value: "NY", label: "New York" },
  { value: "NC", label: "North Carolina" },
  { value: "ND", label: "North Dakota" },
  { value: "OH", label: "Ohio" },
  { value: "OK", label: "Oklahoma" },
  { value: "OR", label: "Oregon" },
  { value: "PA", label: "Pennsylvania" },
  { value: "RI", label: "Rhode Island" },
  { value: "SC", label: "South Carolina" },
  { value: "SD", label: "South Dakota" },
  { value: "TN", label: "Tennessee" },
  { value: "TX", label: "Texas" },
  { value: "UT", label: "Utah" },
  { value: "VT", label: "Vermont" },
  { value: "VA", label: "Virginia" },
  { value: "WA", label: "Washington" },
  { value: "WV", label: "West Virginia" },
  { value: "WI", label: "Wisconsin" },
  { value: "WY", label: "Wyoming" },
  { value: "DC", label: "District of Columbia" },
];

export const STATE_EFFECTIVE_RATE = {
  AL: 0.04,
  AK: 0,
  AZ: 0.025,
  AR: 0.043,
  CA: 0.067,
  CO: 0.044,
  CT: 0.05,
  DE: 0.05,
  FL: 0,
  GA: 0.046,
  HI: 0.063,
  ID: 0.058,
  IL: 0.0495,
  IN: 0.0315,
  IA: 0.045,
  KS: 0.048,
  KY: 0.045,
  LA: 0.04,
  ME: 0.058,
  MD: 0.055,
  MA: 0.05,
  MI: 0.0425,
  MN: 0.06,
  MS: 0.04,
  MO: 0.047,
  MT: 0.053,
  NE: 0.052,
  NV: 0,
  NH: 0,
  NJ: 0.057,
  NM: 0.047,
  NY: 0.062,
  NC: 0.045,
  ND: 0.026,
  OH: 0.035,
  OK: 0.04,
  OR: 0.075,
  PA: 0.0307,
  RI: 0.05,
  SC: 0.045,
  SD: 0,
  TN: 0,
  TX: 0,
  UT: 0.0485,
  VT: 0.053,
  VA: 0.048,
  WA: 0,
  WV: 0.045,
  WI: 0.053,
  WY: 0,
  DC: 0.06,
};

export const FEDERAL_BRACKETS = {
  single: [
    { upTo: 11600, rate: 0.1 },
    { upTo: 47150, rate: 0.12 },
    { upTo: 100525, rate: 0.22 },
    { upTo: 191950, rate: 0.24 },
    { upTo: 243725, rate: 0.32 },
    { upTo: 609350, rate: 0.35 },
    { upTo: Infinity, rate: 0.37 },
  ],
  married_joint: [
    { upTo: 23200, rate: 0.1 },
    { upTo: 94300, rate: 0.12 },
    { upTo: 201050, rate: 0.22 },
    { upTo: 383900, rate: 0.24 },
    { upTo: 487450, rate: 0.32 },
    { upTo: 731200, rate: 0.35 },
    { upTo: Infinity, rate: 0.37 },
  ],
  married_separate: [
    { upTo: 11600, rate: 0.1 },
    { upTo: 47150, rate: 0.12 },
    { upTo: 100525, rate: 0.22 },
    { upTo: 191950, rate: 0.24 },
    { upTo: 243725, rate: 0.32 },
    { upTo: 365600, rate: 0.35 },
    { upTo: Infinity, rate: 0.37 },
  ],
  head_of_household: [
    { upTo: 16550, rate: 0.1 },
    { upTo: 63100, rate: 0.12 },
    { upTo: 100500, rate: 0.22 },
    { upTo: 191950, rate: 0.24 },
    { upTo: 243700, rate: 0.32 },
    { upTo: 609350, rate: 0.35 },
    { upTo: Infinity, rate: 0.37 },
  ],
};

export const BANK_PLATFORM_HINTS = new Set([
  "stripe",
  "wise",
  "bank",
  "plaid",
  "quickbooks",
  "xero",
  "bank_account",
  "banking",
  "paypal",
]);
